# Generated by Django 4.2 on 2025-08-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='age',
        ),
        migrations.AddField(
            model_name='clients',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
    ]
