# Generated by Django 4.2 on 2025-08-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_clients_age_clients_birthday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='clients',
        ),
        migrations.AddField(
            model_name='clients',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='ClientControl',
        ),
        migrations.DeleteModel(
            name='Treatment',
        ),
    ]
